### ISSUE TITLE
Is Axios supposed to be used in Dotnet excercise? 

### ISSUE THREAD

**Issue by tfsjohan** [microsoft/CopilotHackathon#29]
In the **dotnet** readme.md two references are made to use Axios. Is this correct or a copy / paste error from the Node example?

https://github.com/microsoft/CopilotHackathon/blob/0fe0c184aa268b7af66d08be48d6e1a73a7efba4/exercisefiles/dotnet/README.md?plain=1#L85

https://github.com/microsoft/CopilotHackathon/blob/0fe0c184aa268b7af66d08be48d6e1a73a7efba4/exercisefiles/dotnet/README.md?plain=1#L90

**Comment by cmendible** [comment]
this is a copy paste error.
