### ISSUE TITLE
Making new instances of HttpClient is bad practice

### ISSUE THREAD

**Issue by tfsjohan** [microsoft/CopilotHackathon#30]
https://github.com/microsoft/CopilotHackathon/blob/0fe0c184aa268b7af66d08be48d6e1a73a7efba4/completesolution/dotnet/MinimalAPI/Program.cs#L53

Using `var client = new HttpClient()` is generally considered a bad practice for several reasons. Having that in the solution, might not look good. 

I think this should either be changed to a more proper solution like using DI to get a HttpClient, or using DI to get a HttpClientFactory. How ever, I can also see this is a good learning opportunity to show case when Copilot might make mistakes and it is still really important for the developer to build their skills and make sure the code that Copilot produces is following best practices. 

At the very least, I think it should be obvious that this is intended, even though it's not the recommended way of doing things.

**Comment by cmendible** [comment]
indeed it is. Do you mind contributing with a PR?

**Comment by tfsjohan** [comment]
Sure. 

Do you think it's better to make sure the finished code is correct, or keep it as is, but add a comment to notify the user to stay alert to these type of "errors"? 

I haven't tried to check what Copilot actually would produce, so maybe it will do this correctly.
